version: '3'

services:
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always


# version: "3"

# services:
#   app:
#     build: .
#     command: npm start
#     ports:
#       - "3001:3001"
#     volumes: 
#       - .:/app